version: '3.9'

services:
  breast_cancer_detection:
    container_name: breast_cancer_detection
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./breast_cancer_detection_system:/breast_cancer_detection
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media
    env_file:
    - ./dotenv_files/.env
    depends_on:
    - psql

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
